// <auto-generated />
namespace SysAcad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criarBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criarBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201906122237264_criarBanco"; }
            get { return "201905312216148_criarbanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
